name: Solar System Workflow
on:
  workflow_dispatch:
  push:
    branches:
        - main
        - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/sampleData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    Unit-Testing:
        name: Unit Testing
        strategy:
          matrix:
            os: [macos-latest]
            node-js-version: [18]
            exclude:
              - node-js-version: 19
                os: macos-latest
        runs-on: ${{ matrix.os }}
        steps:
         - name: Checkout Action
           uses: actions/checkout@v4

         - name: Setup Node Js Version ${{ matrix.node-js-version }} on OS ${{ matrix.os }}
           uses: actions/setup-node@v4
           with:
            node-version: ${{ matrix.node-js-version }}

         - name: Install Dependencies 
           run: npm install

         - name: Unit Testing
           run: npm test

         - name: Upload Artifact
           uses: actions/upload-artifact@v4
           with:
            name: Mocha-Test-Results-${{ matrix.os }}-${{ matrix.node-js-version }}-$(date +%s)-$RANDOM
            path: test-results.xml
            retention-days: 5
    code-coverage:
        name: Code Coverage
        strategy:
          matrix:
            os: [ubuntu-latest]
            node-js-version: [18]
            exclude:
              - node-js-version: 18
                os: macos-latest
        runs-on: ${{ matrix.os }}
        continue-on-error: true
        steps:
         - name: Checkout Action
           uses: actions/checkout@v4

         - name: Setup Node Js Version ${{ matrix.node-js-version }} on OS ${{ matrix.os }}
           uses: actions/setup-node@v4
           with:
            node-version: ${{ matrix.node-js-version }}

         - name: Install Dependencies 
           run: npm install

         - name: Code Coverage
           continue-on-error: true
           run: npm run coverage

         - name: Upload Artifact
           uses: actions/upload-artifact@v4
           with:
            name: Code-Coverage-Results-${{ matrix.os }}-${{ matrix.node-js-version }}-$($date +%s)-$RANDOM
            path: coverage
            retention-days: 5

        # - name: Download Artifact
        #   uses: actions/download-artifact@v4
        #   with:
        #    name: Mocha-Test-Results
